### ISSUE TITLE
Browser-Unabhängigkeit

### ISSUE THREAD

**Issue by cstenkamp** [OsnaCS/avz-run#132]
Es scheint mir als testen alle nur auf Firefox?

Was mir als Chrome-User auffällt ist, dass sounds (z.B. doorsounds) nicht klappen, und der bildschirm durchgehend rot bleibt nachdem man in Feuer tritt, auch wenn man wieder raus ist

**Comment by dahaupt** [comment]
Wir sollten zumindest **Firefox** und **Chrome** komplett unterstützen. **Microsoft Edge** unterstützt WebGL auch schon recht gut, wobei z.B. die GUI nicht angezeigt wird. Ältere Internet Explorer kann man meist vergessen und können aus meiner Sicht ignoriert werden.

**EDIT:** Bei einem meiner nächsten Commits dürfte die GUI auch im Microsoft Edge korrekt angezeigt werden.

**Comment by Djuelich** [comment]
dahaupt und ich fixen gerade den Sound BUGen man hat wenn man chrome benutzt (footsteps und atmosphere sind nur übern rechten audiokanal hörbar).

**Comment by Djuelich** [comment]
Bei Chrome liegt das Problem darin, das alle sounds(die an der Kamera geheftet sind) nur über den rechten kanal abgespielt werden. Alle anderen werden in Stereo abgespielt.

**Comment by dahaupt** [comment]
@cstenkamp @Djuelich Damit sollten Chrome und Firefox (bis auf die Performance) jetzt gleich arbeiten. Falls noch ein Problem auftritt, einfach hier kommentieren.
