### ISSUE TITLE
Map Editor

### ISSUE THREAD

**Issue by ThomasDautzenberg** [OsnaCS/avz-run#136]
XMLHandler          ~{Andreas}~
- final filename -> constructor
- methode createLevelFromXML(String file)
- methode createRoomFromXML(String name) [bleibt]
- methode toXML(Level level)
- methode writeXML(Level level)
- methode clear [bleibt]
- 

DrawingPanelViewController  ~{Laura}~
- kümmert sich um alles
- neuer roomlistener erstellt jedes mal wenn room gesetzt wird
- 

Level               ~{Barbara}~
- implements NodeList
- hat allrooms, allways

Roomlistener            ~{Barbara}~
- Point mausposition, Level level, Room room [koordinatentyp von room benutzen!]
- constructor(String name, Level level) [Room wird erstellt]
- methode updateLevel
- 

Koordinatentyp          ~{Laura}~
- [final double x,y ; double posx, posy, int winkel (bogenmaß)]
- berechnet integerkoordinaten (scaled)
- berechnet rotation, translation und abstand von punkten
- addkoordinatentypen (kt1, kt2)

Room                ~{Thomas}~
- extends drawable object
- hat 3 Koordinatentypen (a,e,center)
- hat eine liste von wegen
- methoden: rotation, translation
- paintmethode (malt wege.paint mit)
- constructor: double a,e,center ; waylist
- constructor: string name
- methode: compareWay(allways)  [returns allways]
  .bei true: connect
- methode: private connect(way1, way2) [ändert eigene position]

Weg             ~{Tom}~
- extends DrawableObject (line)
- hat Koordinatentyp pos, normale(?) [normalen zeigen nach außen]
- methode: compareDistance [normalen müssen aufeinander zeigen]
- methode: normaleBerechnen
- methode: allgemeinePos [papa.center+pos]
- Room papa
- hat paintmethode

**Comment by tkruemmel** [comment]
Way ist fertig und muss getestet werden

**Comment by ThomasDautzenberg** [comment]
Struktur für die Datei die vom Editor ausgegeben wird:

[level_test.txt](https://github.com/OsnaCS/avz-run/files/393280/level_test.txt)

**Comment by ThomasDautzenberg** [comment]
Room bis auf Paintmethode fertig

**Comment by ThomasDautzenberg** [comment]
- Tom

Kommentieren

Way
 . paintmethode überarbeiten
- Andreas

Kommentieren

RoomListener
 . getter und setter für level
- Thomas

Kommentieren

Room
 . schnittstelle zu coordinates

Coordinates
 . basisUmrechnungen
- Laura & Barbara

Kommentieren

DrawingPanelViewController 
 . hat level (wird in listenern geändert)

 . delegates zurücksetzen
 . buttons implementieren (speichern, undo[, redo], clear)

**Comment by ThomasDautzenberg** [comment]
Bugs zu fixen:
- Thomas

Paintmethode von Room soll die Nullpunktverschiebung berücksichtigen
- Laura

Level soll bei Reset einen Center-Room in die Mitte setzen
Center sollte sinnig gezeichnet werden
- Andreas & Barbara

XMLreset an seltsamer Stelle sollte behoben werden (exit?)
mousemove updated aus irgendeinem grund noch die XML
- Tom

Wegzeichnung sollte funktionieren

**Comment by AndreasSchroeder** [comment]
Wege werden korrekt gemalt

**Comment by tkruemmel** [comment]
Wenn man cleart, können keine neuen Räume mehr im XML gespeichert werden.

**Comment by ThomasDautzenberg** [comment]
damit türen rausgenommen werden, in room.compareWays eine zeile über added=true folgendes einfügen:

mapway.getFather().getWaylist().remove(mapway);
