### ISSUE TITLE
Neue Items: Medipack, Taschenlampe, Chimani

### ISSUE THREAD

**Issue by cstenkamp** [OsnaCS/avz-run#155]
-dass die Rennzeit nur runtergeht wenn man dabei auch pfeiltaste drückt
-die nebelzeit vom raum abhängig machen (siehe das segments-objects)
Taschenlampe kann man aufnehmen und hat dann ein strahlelicht,
Medipack hängt an Wänden (tut es im AVZ wirklich öfter), und stellt 1/4 leben wieder her...

Und Chimani steht in irgendeinem lectureroom und hält die Vorlesung.
Der Charakter muss nicht erkennbar sein, hauptsache sein mesh trägt jeden Tag als Textur eins von 200 Tshirts, zufällig ausgewählt. Sobald man den Vorlesungsraum in dem er gerade lecture hält betritt, muss man sich in die erste Reihe setzen und dort bleiben.

**Comment by ThomasDautzenberg** [comment]
Welches Item genau ist egal. Aber wir brauchen einen Vornberger-Mode. Immunität gegen Feuer und John Cena Musik.

**Comment by mwygas** [comment]
AND HIS NAME IS JOHN CENA! :laughing:
