### ISSUE TITLE
Stuff vom Montag der 3. Woche: FIXES(Important) 

### ISSUE THREAD

**Issue by cstenkamp** [OsnaCS/avz-run#158]
-pointerlocks und spezielle türen 
- (Gefixt) Code-Türen und Transponder-Türen klappen nicht
  (scheint nicht mehr vorzukommen?) -hinter feuern ist immer nen kommen und gehen von schwarzen flächen
  (DONE) -ne weltkugel im hintergrund
  (DONE) -ne Funktion, die vor dem laden der rooms.xml geladen wird, die <spawn index="stuhl1" position="(-1.2 bis 5.4 step 0.6, 2 bis 14 step 1, 0)" object="pult" normaltowall="(1,0)" scale="1"/> entpsrechend ersetzt
- (gefixt) Das Raycasten: Man sieht nicht direkt ob man pickupables pickupen kann; man springt sehr sehr sehr oft druch den boden, man kann durch 1 px breite spalte durchlaufen
- (fix) Wenn man shift und c gleichzeitig drückt kommt man durch sämtliche wände

**Comment by dahaupt** [comment]
> - hinter feuern ist immer nen kommen und gehen von schwarzen flächen 

Wird soweit ich weiß durch eine Skybox behoben von @a-hain  :+1: 
(jedoch noch nicht commited)

**Comment by dbarthol** [comment]
man sollte die Spielerhöhe ändern spieler höhe passt nicht zur Umgebung und Stimme

**Comment by a-hain** [comment]
skybox ist online (braucht evt noch einen kleinen fix)

@dbarthol: in firstPerson.js lässt sich PLAYERHEIGHT ändern. inzwischen passen sich auch alle anderen spielerbezogenen konstanten darauf an.

**Comment by Sefrin** [comment]
Raycasting mit "pickupables" ist fixed,
shift+c bug sollte weniger zuverlässig funktionieren.. kann bei niedrigen fps aber immernoch vorkommen
