### ISSUE TITLE
Stuff vom Montag der 3. Woche: Nice 2 have

### ISSUE THREAD

**Issue by cstenkamp** [OsnaCS/avz-run#162]
-chimanis vorlesung, nen Chimani mit einem von 200 Tshirst
-die nebelzeit vom raum abhängig machen (siehe das segments-objects)
-dass die Rennzeit nur runtergeht wenn man dabei auch pfeiltaste drückt
-und dass das rennen-hochrunter auch nur dann passiert wenn man dabei auch tatsächlich vorwärts kommt (nicht vor wand)
-und dass man sich nicht durch stuhlreihen buggen kann :/
-Medipack und Taschenlampe

**Comment by dbarthol** [comment]
Wir brauchen eine Bewegungsfunktion für den Roboter, er sollte auf einer durch Punkte vorgegebene Route patrouillieren. :)

--> wir kümmern uns jetzt selbst darum :(

**Comment by dahaupt** [comment]
> dass die Rennzeit nur runtergeht wenn man dabei auch pfeiltaste drückt

@cstenkamp: Das sollte mittlerweile eingebaut sein.
