### ISSUE TITLE
Performanceverbesserung

### ISSUE THREAD

**Issue by Djuelich** [OsnaCS/avz-run#207]
Fixes von FPS einbrüchen und FPS-Verbesserung

**Comment by dahaupt** [comment]
Veränderung der meisten Materials zu Lambert hat schon viel gebracht (Credits an @Sefrin).
Die PointLights in den Feuern können aber an gewissen Stellen zu deutlichen FPS-Drops führen.

Generell ist die Performance jedoch schon deutlich besser geworden, besonders im Chrome.
