### ISSUE TITLE
Pförtnerebene AVZ

### ISSUE THREAD

**Issue by MiriamBeutel** [OsnaCS/avz-run#24]

**Comment by ThomasDautzenberg** [comment]
http://threejs.org/editor/

**Comment by ThomasDautzenberg** [comment]
Erstellung des AVZ-Grundlevels in Einzelteilen (Halle, Gang)

**Comment by cstenkamp** [comment]
AVZ-RUN - Issue: Pförtnerebene AVZ

Was wir tun: Versuchen die Pförtnerebene des AVZs in Three.js darzustellen, wenn auf einfache Weise möglich, allerdings auch mehr Stockwerke.
Was wir haben: Quellcode einer Diplomarbeit von 1998 (dank Prof. Vornberger), welche in VRML das gesamte AVZ gebaut hat.
Wir versuchen also, diese VRML-Dateien zu Three.js zu portieren, und wenn das nicht möglich ist, uns die Szenen in Three.js selbst zu bauen.

WIR BRAUCHEN
-Hauptflur (2., 3., 4. stock)
-Vorflur
-Hauptflur mit Pförtner (1. stock)
-Rundgang mit Mittelbüros
-Gang ohne Mittelbüros 
-Treppen (?)
-min. 1 Prototyp Büro
-Fenster & Türen (Enden der jew. Segmente)

IN VRML GEFUNDEN
-Bürostühl

FRAGEN
-Wie groß sind einzelne Teile, wie kann man die aneinander packen?

KONVENTIONEN
-Alle Exporte der AVZ-Teile sind im JSON-Dateiformat (für Three.js)

**Comment by ThomasDautzenberg** [comment]
Grundlagen für den Kartenerstellungs-Algorithmus:

Kartenstücke werdne in .json gespeichert und haben einen Eintrag in einer .xml-Datei. Dieser Eintrag beinhaltet die Größe des Stücks, sowie Türen und Spawnpunkte.
Türen haben eine Normale und einen Typ, um weitere Kartenstücke richtig anzufügen.
Spawnpunkte haben ebenfalls eine Normale die Richtung Wand zeigt, da die meisten Objekte an der Wand hängen oder stehen. Außerdem ist in einem Tag festgelegt um was für eine Art von Objekt es sich handelt (spezifisch oder allgemein dh. von "Tisch" bis "usable").

Objekte selbst erhalten eine eigene .xml-Datei. Details werden hier noch entwickelt, sind aber zu ersten Kartenerstellung nicht wichtig.

TODO:
Kartenstücke ausmessen und normalisieren (sodass sie auf dem Boden 'liegen' und die richtige Höhe haben)

**Comment by ThomasDautzenberg** [comment]
angelehnt an den aviator quellcode, erstellen wir ein segment für jedes kartenstück als mesh. anschließend werden an tür-orte türen und uU weitere segmente angefügt (die mit den neuen koordinaten und entsprechender ausrichtung erstellt werden)

**Comment by mwygas** [comment]
// Die Schleife ist dafür da, damit nur eine Seite der Objekte gerendert wird
material.materials.forEach(function (e) {
                if (e instanceof THREE.MeshPhongMaterial || e instanceof THREE.MeshLambertMaterial) {
                    e.side = THREE.FrontSide;
                }
            });
// Glättet die Objekte
geometry.mergeVertices();
geometry.computeVertexNormals();
