### ISSUE TITLE
Kamerasteuerung

### ISSUE THREAD

**Issue by MiriamBeutel** [OsnaCS/avz-run#25]

**Comment by lauraHem** [comment]
Kamerasteuerung mit WASD und Maus
Sprung und Ducken
Kollision anhand einer unsichtbaren Kugel um die Kamera
Tests in einer simplen Umgebung

**Comment by Sefrin** [comment]
First version ready to use. Remaining issue: collision with ground is unreliable, might fall through objects when jumping/crouching on them. Setting ray length to 10 fixed it for me. Will try tomorrow.
