### ISSUE TITLE
Objekte + Texturen

### ISSUE THREAD

**Issue by MiriamBeutel** [OsnaCS/avz-run#26]

**Comment by MelissaSteininger** [comment]
Objekte:

Stuhl 1 holz            +   Andreas
Stuhl 2 büro           +   vorhanden
Stuhl 3 eingeklappt     +   Barbara
Tisch 1             +   Melissa
Tisch 2 (Hörsaal)      +   Barbara
Feuerlöscher           +   David
Waschbecken         o      Tom
Toilettenkabinen        -
Tafel               +   Eduard
Kreide + Schwamm        -  
Tür 1 nomale           +   Martin
Tür 2 doppel           o  
Fenster             +   Melissa
eingestürzte Wände        +   Andreas
Feueraxt            o      Andreas
Trümmerteile           +   Martin
Lampe               +   Eduard
PCs             +   Tom
Roboter?            -
Mülleimer          o  Andreas
Waschlappen?            -
Getränkeautomat            -
Notausgangschild        +   David
Beamer              o Tom
OHP             -
Steckdosen          -
Fluchplan           o  
Plakate             +   Tom
Blätter                o
Bücherregal- vorhanden

**Comment by mwygas** [comment]
blender ninja tutorial:
http://cgi.tutsplus.com/tutorials/creating-a-low-poly-ninja-game-character-using-blender-part-1--cg-16132

**Comment by cstenkamp** [comment]
Drehstuhl haben wir schon im VRML-Modell gefunden, müsst ihr nicht mehr machen :)

**Comment by cstenkamp** [comment]
Hier ganz viele Texturen (und Objekte, welche wir mal Versuchen zu JSON zu konvertieren)

> Hier ist der Einstieg in die Single-User-Welt:
> 
> http://www-lehre.informatik.uos.de/~blaxxun/BxxWorlds/avz/html/main_singleuser.html
> 
> Ich lege mal die Quellen für 3 Tage in meine Dropbox ( etwa 1 GB):
> 
> https://www.dropbox.com/sh/bm3dibh7h1oc6nf/AADwh6nftJPUp54hD03Qspb_a?dl=0

**Comment by AndreasSchroeder** [comment]
Der erste Stuhl und die zerstörte Wand ohne Texturen sind fertig

**Comment by AndreasSchroeder** [comment]
Objekte:

(done) Stuhl 1 holz + Andreas
Stuhl 2 büro + Tom
Stuhl 3 eingeklappt + Barbara
Tisch 1 + Melissa
Tisch 2 (Hörsaal) + Barbara
Feuerlöscher + David
Waschbecken o
Toilettenkabinen -
Tafel + Eduard
Kreide + Schwamm -

Tür 1 nomale + Martin
Tür 2 doppel o

Fenster + Melissa
(done)eingestürzte Wände + Andreas
 Feueraxt o Andreas
Trümmerteile + Martin
Lampe + Eduard
PCs + Tom
Roboter? -
(done) Mülleimer o Andreas
Waschlappen? -
Getränkeautomat -
Notausgangschild + David
Beamer o
OHP -
Steckdosen -
Fluchplan o

Plakate + Tom
Blätter o

**Comment by dbarthol** [comment]
habe Feuerlöscher und notausgangsschild ohne Texturen fertig.

**Comment by AndreasSchroeder** [comment]
Modell von Mülleimer, Feueraxt und OHP fertig

**Comment by AndreasSchroeder** [comment]
Mache jetzt die Toilettenkabinen

**Comment by AndreasSchroeder** [comment]
andreas.schroeder89@gmail.com

**Comment by MelissaSteininger** [comment]
msteininger@uos.de

**Comment by dbarthol** [comment]
dbarthol@uos.de

**Comment by EduardRempel** [comment]
eduardrempel@gmx.de

**Comment by BarbaraButz** [comment]
bbutz@uos.de

**Comment by mwygas** [comment]
https://trello.com/invite/avzrun/bcf2160d7aec49aa1d002b04b0a60d67

**Comment by AndreasSchroeder** [comment]
So gibt es keine Fehler mit der URI beim öffnen Lokaler Datein in Firefox:

Firefox

```
Go to about:config
Find security.fileuri.strict_origin_policy parameter
Set it to false
```

(https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally)
