### ISSUE TITLE
Bug - Aus dem Level springen

### ISSUE THREAD

**Issue by tkruemmel** [OsnaCS/avz-run#262]
An hochgelegenen Punkten wie der Treppe am Anfang oder Tischen (im LEctureroom zumindest) ist es möglich aus dem Level zu springen.

**Comment by dbarthol** [comment]
Bin gerade auch noch durch den Boden im groundlevel gefallen. Bis dahin lief aber alles gut. Weiss nicht ob wir das noch wegbekommen. Wäre schade in der Präsentation.
