### ISSUE TITLE
Feuer und Rauch

### ISSUE THREAD

**Issue by MiriamBeutel** [OsnaCS/avz-run#27]

**Comment by Djuelich** [comment]
- Simulation eines Feuer mit hilfe einer .png (Partikel sind schlecht für die performance)
- suchen nach einem passendem Rauch-system 
- sichteinschränkung durch fog welches gräulich ist (simulation des Rauches im Raum)
- verwendung eines Beispiellevels zur Performanceprüfung

**Comment by dahaupt** [comment]
[Vorläufige Ordnerstruktur AVZ RUN.txt](https://github.com/OsnaCS/avz-run/files/373143/Vorlaufige.Ordnerstruktur.AVZ.RUN.txt)

**Comment by Djuelich** [comment]
Rauchsimulation im Beispielraum erfolgreich (kleines Feature: Rauch verdichtet sich mit fortschreitender Zeit)

**Comment by Djuelich** [comment]
Feuer und Rauch Issue ist abgearbeitet.
