### ISSUE TITLE
Bug - Mehrere Transponder sind immer gleich programmiert

### ISSUE THREAD

**Issue by tkruemmel** [OsnaCS/avz-run#271]
Wenn man mehrere Transponder programmiert haben alle die Berechntigung des letztes

**Comment by a-hain** [comment]
Es besteht momentan keine Notwendigkeit, das zu beheben oder anders zu programmieren (was sich meiner Meinung nach wohl kaum noch ändern wird), weil es in dem ganzen Spiel nur einen Transponder gibt.

**Comment by dahaupt** [comment]
@MiriamBeutel @a-hain Dann kann das hier wohl geschlossen werden :)

**Comment by cstenkamp** [comment]
habs gefixt, ist jetzt pro level

**Comment by dahaupt** [comment]
@MiriamBeutel Dann ist dieser Issue ebenfalls zu schließen :+1: :rocket:
