### ISSUE TITLE
Beschreibung zum Ausführen/Testen in der README

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/avz-run#56]
Manchmal kommen so doofe Leute, wie ich, daher und wollen einfach mal gucken, was andere Gruppen so tun. Es wäre gut, wenn in der README steht, wie ich dieses Projekt ausprobieren kann :wink:

**Comment by cstenkamp** [comment]
Hehehe...

**Comment by LukasKalbertodt** [comment]
![Hehehe](http://i.imgur.com/meftV0q.gif)
