### ISSUE TITLE
Spielabend

### ISSUE THREAD

**Issue by MiriamBeutel** [OsnaCS/avz-run#63]
Kommentiert diesen Issue ggf. mit dem Spiel und den Snacks/Getränken die ihr mitbringt :)

**Comment by ThomasDautzenberg** [comment]
Flips würd ich mitbringen und als Spiele auf jeden Fall Abluxxen und Bohnanza.

**Comment by ThomasDautzenberg** [comment]
Spielt eigentlich jemand Magic?

**Comment by a-hain** [comment]
Hätte Cards against Humanity und würde bisschen was an Säften mitbringen.

**Comment by dbarthol** [comment]
Ich bringe Dumm gelaufen und ne Tüte Chips mit.

**Comment by BarbaraButz** [comment]
An Spielen hätte ich Tabu, Werwolf, Uno, Dobble, Wizard, gemischtes Doppel, Phase 10 (vllt. mehr). Ansonsten könnte ich noch ein paar Getränke mitbringen (Apfelschorle oder Limo oder sowas.)

**Comment by Fufukuschelipu** [comment]
Ich bringe mit:
 Spiele . Halt mal Kurz
                zweites Wizzard
Essen : Trauben-Gauda -Spieße
              Minisalami- Essiggruken Spieße

**Comment by mwygas** [comment]
Halli Galli und noch was zum snacken

**Comment by AndreasSchroeder** [comment]
Ich bringe einen Sixer Schöfferhoffer alkoholfrei mit und Nobody is perfect.

**Comment by tkruemmel** [comment]
4 cl   Wodka
2 cl    Likör (Peach Tree)
2 cl    Zitronensaft
1 cl    Grenadine
4 cl    Orangensaft
4 cl    Ananassaft 

Sex on the beach Zutaten.
Ich bringe einen Orangensaft mit und ein Netz Zitronen.
Grenadine: Martin?
Vodka: Daniel 
Pfirsichsirup: Laura 
Pfirsichlikör:  Martin?
Ananassaft: Laura
Ananassaft: Chris
Becher: Chris
1 Packung Orangensaft:Miriam

**Comment by Sefrin** [comment]
Munchkin Apokalypse, Eistee aus eigener Herstellung, Mangos

**Comment by cstenkamp** [comment]
Feeette munchkin runde? Munchkin beißt hier
