### ISSUE TITLE
Präsentation als Sicherheitsunterweisung

### ISSUE THREAD

**Issue by Fufukuschelipu** [OsnaCS/avz-run#88]
Als erste Idee schlage ich vor ,dass die Präsentation als Sicherheitsunterweisung dartstellen. Dabei  tragen wir dann Sichheitswesten, Laborkittel oder andere Ding tragen, die Sicherheit repräsentieren.
 ^(\* . *)^

**Comment by Djuelich** [comment]
ich habe dienstklamotten vom  rettungsdienst ;D

**Comment by jonas-schievink** [comment]
:bangbang:

**Comment by Fufukuschelipu** [comment]
a wilde jonas-schievink appeared :O
